package com.example.dominionhelper.model

import com.example.dominionhelper.R

enum class Set (val imageId: Int = R.drawable.ic_launcher_foreground) {
    BASE(R.drawable.set_unknown),
    BASE_1E(R.drawable.set_dominion_1e),
    BASE_2E(R.drawable.set_dominion_2e),
    INTRIGUE(R.drawable.set_unknown),
    INTRIGUE_1E(R.drawable.set_intrigue_1e),
    INTRIGUE_2E(R.drawable.set_intrigue_2e),
    SEASIDE(R.drawable.set_unknown),
    SEASIDE_1E(R.drawable.set_seaside_1e),
    SEASIDE_2E(R.drawable.set_seaside_1e),
    ALCHEMY(R.drawable.set_alchemy),
    PROSPERITY(R.drawable.set_prosperity),
    PROSPERITY_1E(R.drawable.set_prosperity),
    PROSPERITY_2E(R.drawable.set_prosperity),
    CORNUCOPIA(R.drawable.set_cornucopia),
    HINTERLANDS(R.drawable.set_hinterlands),
    HINTERLANDS_1E(R.drawable.set_hinterlands),
    HINTERLANDS_2E(R.drawable.set_hinterlands),
    DARK_AGES(R.drawable.set_dark_ages),
    GUILDS(R.drawable.set_guilds),
    ADVENTURES(R.drawable.set_adventures),
    EMPIRES(R.drawable.set_empires),
    NOCTURNE(R.drawable.set_nocturne),
    RENAISSANCE(R.drawable.set_renaissance),
    MENAGERIE(R.drawable.set_menagerie),
    ALLIES(R.drawable.set_allies),
    PLUNDER(R.drawable.set_plunder),
    RISING_SUN(R.drawable.set_rising_sun),
    PROMO(R.drawable.set_promo),
    CORNUCOPIA_GUILDS(R.drawable.set_unknown),
    CORNUCOPIA_GUILDS_1E(R.drawable.set_unknown),
    CORNUCOPIA_GUILDS_2E(R.drawable.set_unknown),
    PLACEHOLDER() // TODO
}

enum class Type {
    ACTION,
    ATTACK,
    REACTION,
    CURSE,
    DURATION,
    TREASURE,
    VICTORY,
    NIGHT,
    PRIZE,
    RUINS,
    TRAVELLER,
    GATHERING,
    LIAISON,
    DOOM,
    HEIRLOOM,
    CASTLE,
    SHELTER,
    SPIRIT,
    FATE,
    REWARD,
    COMMAND,
    LOOTER,
    KNIGHT,
    RESERVE,
    EVENT,
    LANDMARK,
    ZOMBIE,
    BOON,
    HEX,
    STATE,
    PROJECT,
    PLUNDER,
    TRAIT,
    SHADOW,
    LOOT,
    ALLY,
    TOWNSFOLK,
    ODYSSEY,
    CLASH,
    FORT,
    WIZARD,
    AUGUR,
    WAY,
    ARTIFACT,
    OMEN,
    PROPHECY
}

enum class Category {
    CANTRIP,
    NONTERMINAL_DRAW,
    TERMINAL_DRAW,
    CURSER,
    NONTERMINAL, // Skipped: Cantrips, Villages, Non-terminal draw, peddlers, disappearing money
    TERMINAL, // Skipped: Way too many cards
    THRONEROOM_VARIANT,
    VILLAGE,
    TRASHER,
    ALT_VP,
    PLUSBUY,
    DECK_INSPECTOR,
    TRASH_FOR_BENEFIT,
    HANDSIZE_ATTACK,
    // ^done
    DIGGING,
    DISCARD, // For benefit
    SIFTERS, // ?
    COST_REDUCTION,
    DISAPPEARING_MONEY,
    PEDDLER,
    TERMINAL_SILVER, // ?
    VIRTUAL_COIN,
    VIRTUAL_BUY, // ?
    ATTACK_IMMUNITY,
    DECK_INSPECTION,
    DECK_ORDER_ATTACK,
    JUNKING_ATTACK,
    TRASHING_ATTACK,
    TURN_WORSENING_ATTACK, // ?
    DURATION_DRAW,
    COMMAND_VARIANT,
    GAINER,
    NON_ATTACK_INTERACTION,
    ONE_SHOT,
    REMODELER,
    SPLIT_PILE,
    TOP_DECKER,
    VANILLA, // ?
    EXTRA_TURN // ?
}